name: safe_debouncer
description: A safe, async-aware debouncer for Dart & Flutter that prevents overlapping executions and timer leaks.
version: 0.1.0
homepage: https://github.com/priyeshchowta/safe_debouncer
repository: https://github.com/priyeshchowta/safe_debouncer
issue_tracker: https://github.com/priyeshchowta/safe_debouncer/issues

environment:
  sdk: ">=2.18.0 <4.0.0"

# dependencies:
  # Pure Dart package â€“ no runtime dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0

flutter:
  uses-material-design: false
